version: '3.1'
services:
  redis:
    image: redis:latest
    container_name: redis_6.0.9
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --requirepass 123456